# Generated by Django 4.0.4 on 2022-05-24 05:31

from django.db import migrations, models
import django.db.models.deletion
import galerie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte jmeno autora:', max_length=100, unique=True, verbose_name='Jmeno autora')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('year', models.IntegerField(blank=True, help_text='Zadejte rok vzniku:', null=True, verbose_name='Year')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Price')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='galerie.author')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to=galerie.models.attachment_path, verbose_name='File')),
                ('type', models.CharField(blank=True, choices=[('audio', 'Audio'), ('image', 'Image'), ('text', 'Text'), ('video', 'Video'), ('other', 'Other')], default='image', help_text='Select allowed attachment type', max_length=5, verbose_name='Attachment type')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galerie.painting')),
            ],
            options={
                'ordering': ['type', '-last_update'],
            },
        ),
    ]
