# Generated by Django 4.0.4 on 2022-05-24 05:36

from django.db import migrations, models
import galerie.models


class Migration(migrations.Migration):

    dependencies = [
        ('galerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=galerie.models.attachment_path, verbose_name='Picture'),
        ),
    ]
